### ISSUE TITLE
Dynamic Process Name Resolution

### ISSUE THREAD

**Issue by ppenna** [nanvix/microkernel#3]
**Description**

Currently, the naming service relies on a static scheme  for resolving processes names.

To enable maximum flexibility, we should add an interface for dynamically adding, querying and removing names from the naming table.

**Roadmap**

- [x] Introduce a function to dynamically add a name to the naming table.
- [x] Write a routine for querying process names.
- [x] Add a functionality for removing a name from the naming table.
- [x] Deploy a stand alone naming service.
- [x] Update the naming service client accordingly to rely on the above functionalities.

**Comment by jordanjean** [comment]
The code of the name server has been written. As we need isolated services running on IO cluster to ensure the system works properly, a ticket has been submitted to ask Kalray the way to deploy several binaries on the north IO cluster.

**Comment by ppenna** [comment]
@jordanjean Meanwhile I think that we can keep moving with a multithreading implementation....

**Comment by jordanjean** [comment]
I have conducted tests on _iocluster-test_ branch which consist of running 10 threads on a single IO cluster, and allocate 2GB of memory on both IO clusters. As a conclusion we can spawn more than 4 threads on a single IO cluster, and each IO cluster is connected to a 2GB DDR module.

**Comment by ppenna** [comment]
@jordanjean cool! Then we should proceed on implementing the standalone naming service. I would suggest you to first adapt the mailbox routine accordingly...

**Comment by ppenna** [comment]
Enhancement introduced in commit fc394e878648c27246a899f2233558e0a1e959dc.
